import { ExternalLinkIcon } from '@chakra-ui/icons';
import {
  Box,
  Button,
  Checkbox,
  Container,
  Heading,
  Link,
  SimpleGrid,
  Stack
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

  return (
    <Container maxW="container.md">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as="h1">
          Create <span>T3</span> App
        </Heading>
        <p>This stack uses:</p>
        <SimpleGrid columns={2} spacing="4">
          <TechnologyCard
            name="NextJS"
            description="The React framework for production"
            documentation="https://nextjs.org/"
          />
          <TechnologyCard
            name="TypeScript"
            description="Strongly typed programming language that builds on JavaScript, giving you better tooling at any scale"
            documentation="https://www.typescriptlang.org/"
          />
          <TechnologyCard
            name="Chakra-UI"
            description="Chakra UI is a simple, modular and accessible component library that gives you the building blocks you need to build your React applications"
            documentation="https://chakra-ui.com/"
          />
          <TechnologyCard
            name="tRPC"
            description="End-to-end typesafe APIs made easy"
            documentation="https://trpc.io/"
          />
          <TechnologyCard
            name="Next-Auth"
            description="Authentication for Next.js"
            documentation="https://next-auth.js.org/"
          />
          <TechnologyCard
            name="Prisma"
            description="Build data-driven JavaScript & TypeScript apps in less time"
            documentation="https://www.prisma.io/docs/"
          />
        </SimpleGrid>
        <div>
          <Stack direction="row" spacing={4} align="center">
            <Button colorScheme="teal" variant="solid">
              Button
            </Button>
            <Button colorScheme="teal" variant="outline">
              Button
            </Button>
            <Button colorScheme="teal" variant="ghost">
              Button
            </Button>
            <Button colorScheme="teal" variant="link">
              Button
            </Button>
          </Stack>
          <Stack spacing={5} direction="row">
            <Checkbox colorScheme="red" defaultChecked>
              Checkbox
            </Checkbox>
            <Checkbox colorScheme="green" defaultChecked>
              Checkbox
            </Checkbox>
          </Stack>{" "}
        </div>
        <div>
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
      </main>
    </Container>
  );
};

export default Home;

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <Box shadow="md" p={4}>
      <section>
        <Heading as="h2">{name}</Heading>
        <p>{description}</p>
        <Link href={documentation} isExternal>
          Documentation
          <ExternalLinkIcon mx="2px" />
        </Link>
      </section>
    </Box>
  );
};
